### ISSUE TITLE
Unable to remove document reference

### ISSUE THREAD

**Issue by annabel82** [cairis-platform/cairis#461]
### Expected behaviour
Clicking red - removes (erroneously entered) document reference

### Actual behaviour
HTTP 400

### Steps to reproduce the behaviour
Click red - to remove a document reference

### Version of CAIRIS
2.2.2, this is a fresh pull today 20/10/2019

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Client: Firefox 69.0.3 (64-bit) / Chrome Version 77.0.3865.120 (Official Build) (64-bit) / Mojave 10.14.6

Server Ubuntu 1904 (Server) VM running in KVM Host installed using: 

sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt install curl -y && sudo apt install net-tools -y && curl -s https://cairis.org/quickInstall.sh | bash -s ******************

I have manually worked around this for now by installing nginx/php-fpm on the same VM and exposing adminer and then manually deleting DB entiries in document_reference table

**Comment by failys** [comment]
Thanks for flagging this.  Do you recall what the name of the document reference was?  My suspicion is that there was a reserved character in the name, so the reference shouldn't have been allowed to have been created in the first place.  However, if you can have the string used for the DR name then I reproduce its creation.

**Comment by failys** [comment]
Also, if you get similar problems again, the easiest way of removing erroneous data is to export the model file, get rid of the offending data from the model file and re-import the model.

**Comment by annabel82** [comment]
DR Name is: help you learn your child\'s habits, such as when they are asleep and awake.

I've tried to update the name to simplify it / remove the escaped char / special chars but it just gives me:
 No identifier associated with document_reference object help you learn your child\'s habits, such as when they are asleep and awake

**Comment by failys** [comment]
The problem here is with the Persona Helper as it double escapes factoid names with apostrophes, but I've applied a fix to the server which addresses this.
