### ISSUE TITLE
Trailing \n (new line) in document reference produces 404

### ISSUE THREAD

**Issue by annabel82** [cairis-platform/cairis#466]
### Expected behaviour
Clicking document reference opens it

### Actual behaviour
Error: Request failed with status code 404

### Steps to reproduce the behaviour
Add a document reference with trailing \n (newline)

### Version of CAIRIS
2.2.2, this is a fresh pull yesterday 24/10/2019

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Client: Firefox 69.0.3 (64-bit) / Chrome Version 77.0.3865.120 (Official Build) (64-bit) / Catalina 10.15

Server Ubuntu 1904 (Server) VM running in KVM Host installed using:

sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt install curl -y && sudo apt install net-tools -y && curl -s https://cairis.org/quickInstall.sh | bash -s ******************

### Notes
I have manually worked around this for now by adminer and then manually editing DB entiries in document_reference table, Export here:

INSERT INTO `document_reference` (`id`, `name`, `document_id`, `contributor`, `excerpt`) VALUES
(147,	'Night Vision\n\n',	141,	'AT',	'Night Vision\n\n');

Pretty sure under windows this would have resulted in \r\n\r\n so if you're use some regex to sanitise input you'll need to account for both \n and \r\n methinks.

**Comment by annabel82** [comment]
This reference was added using cairis chrome plugin btw

**Comment by failys** [comment]
Thanks - the problem is that CAIRIS isn't handling escaped characters particularly well.  Working on a fix now.

**Comment by failys** [comment]
I've just pushed a fix that should deal with this.  It doesn't really do anything more than strip out the escape character from object names once they get to CAIRIS, but that should suffice; one would usually want to keep such names short anyway.

**Comment by annabel82** [comment]
Yer the newlines were rogue afaik and didn't appear in the plugin's field
