### ISSUE TITLE
Backslashes / Forwardslashes pruned from Document Reference excerpt name

### ISSUE THREAD

**Issue by annabel82** [cairis-platform/cairis#467]
### Expected behaviour
Ability to use backslashes / forwardslashes in reference name

### Actual behaviour
Backslashes / forwardslashes pruned

### Steps to reproduce the behaviour
Edit document refernce with backslash / forwardslashes

### Version of CAIRIS
2.2.2

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Client: Firefox 69.0.3 (64-bit) / Chrome Version 77.0.3865.120 (Official Build) (64-bit) / Catalina 10.15

Server Ubuntu 1904 (Server) VM running in KVM Host installed using:

sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt install curl -y && sudo apt install net-tools -y && curl -s https://cairis.org/quickInstall.sh | bash -s ******************

### Notes
This might help https://regexr.com/4nj4v

**Comment by failys** [comment]
This is a feature of CAIRIS unfortunately: https://cairis.readthedocs.io/en/latest/reserved.html. This is only pruned from the name though.  This shouldn't be pruned from the excerpt text.

**Comment by annabel82** [comment]
Okay thanks
