### ISSUE TITLE
Error when importing from Trello

### ISSUE THREAD

**Issue by christoms** [cairis-platform/cairis#468]
### Expected behaviour
Successful import from Trello

### Actual behaviour
Error 400 and failed import. Log shows duplicate entries causing errors

### Steps to reproduce the behaviour
Import from Trello then try to import again. The log shows the error "ERROR:cairisd:[400] Database error: Object with name Prefer a brand name already exists.". UI could be improved to reflect the cause of the error.

### Version of CAIRIS
2.2.2

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Downloaded VM from Cairis Google Drive link and run in VMWare Pro
78.0.3904.70 (Official Build) (64-bit) (on host device)

**Comment by failys** [comment]
In this case, the expected behaviour if the persona characteristics have already been imported is that you should get a slightly more informative error message.  I've pushed a fix to the cairis-ui repo that fixes this, so I'll close this once the main repo is update.
