### ISSUE TITLE
Clicking on asset to view details shows Type as Hardware

### ISSUE THREAD

**Issue by annabel82** [cairis-platform/cairis#469]
### Expected behaviour
When clicking on an asset in /objects/asset to view details, the type is reflected in the details window (/objects/asset/name/foo)

### Actual behaviour
The type in the asset details window defaults to Hardware (no 'selected' on the correct `<option>`)

### Steps to reproduce the behaviour
Navigate to /objects/asset and note Type (eg: Information) Click the Asset and note the Type (Hardware)

### Version of CAIRIS
2.2.2

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Client: Firefox 69.0.3 (64-bit) / Chrome Version 77.0.3865.120 (Official Build) (64-bit) / Catalina 10.15

Server Ubuntu 1904 (Server) VM running in KVM Host installed using:

sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt install curl -y && sudo apt install net-tools -y && curl -s https://cairis.org/quickInstall.sh | bash -s ******************

**Comment by failys** [comment]
This problem was raised in Issue 32 in cairis-ui repo and was fixed in the 2.2.3 release. Can you please try reproducing on cairis.bournemouth.ac.uk?

**Comment by annabel82** [comment]
No but I could backup my DB and do  a cairis_update if that's any good?

**Comment by failys** [comment]
If you export your model (a good thing to do early and often) before the cairis_update then you should be fine; manually backing up the MySQL database would be an overkill -  but, yes, if you do this then you’ll get these latest UI updates.

**Comment by annabel82** [comment]
Awesome thanks
