### ISSUE TITLE
Import from Trello

### ISSUE THREAD

**Issue by HarryNoakes** [cairis-platform/cairis#472]
### Expected behaviour
Should import trello affinity diagram within 10 seconds.

### Actual behaviour
Attempts to import remains on processing screen without any control on the interface.

### Steps to reproduce the behaviour
Have an empty list (with no cards in at the start of the board)
![trello](https://user-images.githubusercontent.com/57322293/68087184-1b90fd80-fe4b-11e9-879e-73e2ca4f5857.PNG)

### Version of CAIRIS
2.2.3

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Ubuntu 19.04, Chromium Version 78.0.3904.70 (Official Build) snap (64-bit)

### Details
I tried to import my affinity board from Trello but it would endlessly hang in a loading screen.
Upon Inspecting the web page and looking at the console I see a JS exception of _"Uncaught TypeError: Cannot read property 'trim' of undefined"_ . ![error](https://user-images.githubusercontent.com/57322293/68087149-c7861900-fe4a-11e9-841e-c1f9c089a9fa.png)

Opening up the ImportTrelloView.vue, on line 121 the exception is caused by the trimming of a variable which is undefined. (Most likely the empty list). 
![error2](https://user-images.githubusercontent.com/57322293/68087162-eb495f00-fe4a-11e9-9a81-d0fabcbd32bd.png)

This should be handled either by checking that the list is empty and not importing it, or notifying the user there is an empty list.

**Comment by failys** [comment]
Ignoring empty lists might be the way to go. I’ll look at this over the next few days, but removing empty lists should be a workaround for the time being.

**Comment by failys** [comment]
I've just pushed a fix to the CAIRIS UI which should now (i) raise an error if the list name isn't properly postfixed and (ii) any list has no cards.
