### ISSUE TITLE
Legacy requirement names shown in Model -> Requirement -> Filter by 'Requirement' dropdown

### ISSUE THREAD

**Issue by annabel82** [cairis-platform/cairis#478]
### Expected behaviour
Models -> Requirement -> Filter by 'Requirement' only shows list of current requirements (e.g. 1 req)

### Actual behaviour
Models -> Requirement -> Filter by 'Requirement' shows list of current requirements and names of old (now renamed) requirements (e.g. 2 reqs, old name and new name, selecting old name throws SQL error)

### Steps to reproduce the behaviour
Create a requirement, save it. Change the requirement name to something else, update it. 
Go to Models -> Requirement -> Filter by 'Requirement' and see the old name and the new name listed.

### Version of CAIRIS
2.2.3

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Client: Firefox 70.0.1 (64-bit) / Catalina 10.15.1

Server Ubuntu 1904 (Server) VM running on Fedora KVM Host installed using:

sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt install curl -y && sudo apt install net-tools -y && curl -s https://cairis.org/quickInstall.sh | bash -s ******************

**Comment by annabel82** [comment]
I didn't add this to cairis-ui because I had assumed the UI was just foreaching through (erroneous) data the API was exposing

**Comment by failys** [comment]
That's fine - this seems to be a database problem...

**Comment by failys** [comment]
Should be fixed now, but -- because it's a database update -- you will need to do one of the following: (i) export your model and re-import it, (ii) export your model and re-run update_cairis.

**Comment by annabel82** [comment]
Ok will do that now ty Shamal

**Comment by annabel82** [comment]
Yer fixed ty
