### ISSUE TITLE
Requirement naming consistency 

### ISSUE THREAD

**Issue by christoms** [cairis-platform/cairis#479]
### Expected behaviour
Requirements page headings match requirements entry page

### Actual behaviour
On the requirements list page, reference is made to "description" however, on the requirement entry page it lists "Specification"

### Steps to reproduce the behaviour
Go to requirements page, read table headings then add a new requirement

### Version of CAIRIS
2.2.3

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Chrome on host, using Cairis VM

**Comment by failys** [comment]
Something for the cairis-ui repo, so will close and open an issue there.

**Comment by failys** [comment]
Should now be fixed.
