### ISSUE TITLE
Data flow model filtering

### ISSUE THREAD

**Issue by christoms** [cairis-platform/cairis#480]
### Expected behaviour
Filtering options sorted by type i.e. Entities, data store, process/use case.

### Actual behaviour
List almost randomly generated and no clarity to list

### Steps to reproduce the behaviour
Use filter drop down on Data Flow Model page

### Version of CAIRIS
2.2.3

**Comment by failys** [comment]
This is a good idea, but the implementation detail might need a bit of thought.  In the meantime, I've  pushed an update that at least orders the filter element names for this model.
