### ISSUE TITLE
Install issue & resolution

### ISSUE THREAD

**Issue by jourzero** [cairis-platform/cairis#483]
### Expected behaviour
When running the two smaller install commands as described in https://cairis.readthedocs.io/en/latest/install.html: 
```
sudo docker run --name cairis-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:5.7 --thread_stack=256K
sudo docker run --name CAIRIS --link cairis-mysql:mysql -d -P -p 80:8000 --net=bridge shamalfaily/cairis
```

I should be have no issue.

### Actual behaviour
However, with a current version of Docker (or on Docker for Mac), I get this error with the 2nd command:

`docker: links are only supported for user-defined networks.`

### Steps to reproduce the behaviour
To reproduce, follow the failing install steps mentioned above (from scratch).

### Version of CAIRIS
shamalfaily/cairis:latest  (on 2019/11/14)

### Details of browser or, if applicable, details of the OS used to host CAIRIS
N/A

### Workaround
I've replaced the two first install steps with these commands:

```
NET=cairisnet
docker network create -d bridge $NET
docker run --name cairis-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:5.7 --thread_stack=256K
docker network connect $NET cairis-mysql
docker run --name CAIRIS -d -P -p 80:8000 --net=$NET shamalfaily/cairis

```

**Comment by failys** [comment]
Thanks for flagging this - it's really helpful.  I hadn't run the containers on macOS for a while, but I can reproduce both the problems and fix.  I'll update the documentation for your workaround.
