### ISSUE TITLE
CAIRIS Losing Data (Asset Association Descriptions - Rationale) Upon Export

### ISSUE THREAD

**Issue by JohnLF1995** [cairis-platform/cairis#544]
### Expected behaviour
To not save the asset association descriptions (rationale) and reduces the XML file size once it has been used in CAIRIS.

### Actual behavior
Does not save the asset association descriptions (rationale) and reduces the XML file size once it has been used in CAIRIS.

### Steps to reproduce the behavior
Login and import my file (277kb) and then export the same file back out, it will then be (271kb) and has lost the asset association descriptions.

### Version of CAIRIS
05/06/2020 at 09:15

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Using: http://cairis.bournemouth.ac.uk:8000/

Using Windows 10 Laptop on a Chrome browser.

I have a video demonstrating evidence of this issue in real-time. The author of CAIRIS also holds this video evidence and has been informed that this is an issue.

**Comment by failys** [comment]
The video doesn’t really help me reproduce the problem though. Can you please create a simple model with 2 assets and 1 association to see if this can be reproduced?

**Comment by failys** [comment]
I've found the issue, which relates to how the rationale is being exported (as an attribute of the asset_association element rather than a separate rationale element).
