### ISSUE TITLE
Exporting a .cairis or .xml file with using "&" in a task, asset, use-case

### ISSUE THREAD

**Issue by Jarvis4444** [cairis-platform/cairis#566]
### Expected behaviour
Exports correctly with all tasks, assets and use-cases involving the symbol "&" 
maintained and the ability to import it without issue.

#### CAIRIS
Importing a .cairis file results in an error code with only "X" and no information.
Importing a .xml file results in an error code "Error parsing/tmp/tmp0cvg0zoh.xml: not well-formed (invalid token)"

##### As an XML table
XML Import Error - XML Parse Error - Import Status: Failed

##### As a read-only workbook
Excel Error Popup: "File cannot be opened because: 
Whitespace is not allowed at this location. 
Line 211, Position 24.
asset name="Pictures & Videos" short_code="P&amp;V" type="Infomration" is_critical="0"'"

##### Use the XML Source task pane
Error in XML: Cannot load the specified XML or schema source.

### Steps to reproduce the behaviour
Create a project involving any task, assets and use-cases that involve the AND symbol in their name.

### Version of CAIRIS
Unsure.

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Google Chrome Version 85.0.4138.121 (Official Build) (64-bit)
Running CAIRIS from BU Server

### Additional Information: Solution
Opening the XML file within Notepad++ and removing all traces of any asset, use-case or task that had "&" in its name.

**Comment by failys** [comment]
Ampersands are considered reserved characters in object names: https://cairis.readthedocs.io/en/latest/reserved.html

There is no easy way to stop people adding these via the UI or directly to the model files.  However, on reflection, we could at least tell people when trying to export their models that these characters have creeped into the objects names.   Let me take a look and see what I can do... In the meantime, the work around is to avoid reserved characters in object names.

**Comment by failys** [comment]
I've pushed an update which should stop you exporting models where object names contained reserved characters.
