### ISSUE TITLE
Unable to add association between assets if tail asset is 0th in list.

### ISSUE THREAD

**Issue by fffe0d0a** [cairis-platform/cairis#568]
### Attempted action
Creation of an association between two assets, wherein the tail asset is the first value to appear in the drop-down.

### Expected behaviour
Association is correctly created with intended head and tail connections.

### Actual behaviour
User receives error message stating "Tail Asset is required".

### Steps to reproduce the behaviour
1. Create two or more assets
2. Navigate to the "Associations" tab in one of those assets (Risk > Assets > *your asset* > Environment > Associations)
3. Open Asset Association dialog (green plus icon)
4. Attempt to create an association wherein the "Tail" input is the first value in the provided drop-down.
5. Error message is received, association cannot be created.

### Version of CAIRIS
Master branch

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Cairis server was run on provided [Ubuntu VM](https://cairis.readthedocs.io/en/latest/install.html), after running provided [rebuildServer.sh](https://cairis.org/rebuildServer.sh).

Browsers tested on -
Chromium 85 x64
Firefox 81.0.1 x64
Waterfox 2020.09 x64

**Comment by failys** [comment]
I've tried reproducing this on Chromium, Opera, Firefox and Chromium without any success.  What error message are you getting?

**Comment by fffe0d0a** [comment]
I have included an image of the dialog displaying the error at the top. 
![errorr](https://user-images.githubusercontent.com/26393813/95370179-522f8d80-08d0-11eb-8149-6e7971b42f7b.png)

If Tail is set to any other asset, the association is completed as expected.

**Comment by failys** [comment]
Can you please try doing the following.
1.  Export your model (so you have a copy)
2.  Run the update_cairis script
3.  Once the VM restarts, try re-importing the model to see if you can reproduce the problem.

I made a UI change not long ago that might have fixed this problem, but - depending on when you downloaded or setup your VM - you might not be working with this fix.

**Comment by fffe0d0a** [comment]
I will do so and report back, many thanks.

**Comment by failys** [comment]
If you still get the problem then please upload the simplest model that can reproduce the problem.

**Comment by fffe0d0a** [comment]
I'm afraid I'm still getting this issue. In this example model, I cannot create a reference from A to B, but I can create a reference from A to C.

[cairis_zipped_for_github.zip](https://github.com/cairis-platform/cairis/files/5343158/cairis_zipped_for_github.zip)

**Comment by failys** [comment]
Thanks - I can reproduce this now.  The problem was in the cairis-ui repo, which I've now fixed.  Can you try running update_cairis again (which will update the UI), clean your browser cache, and seeing if you reproduce the problem again?

**Comment by fffe0d0a** [comment]
I can confirm that the issue is now fixed for me after updating cairis. Many thanks for the quick fix.
