### ISSUE TITLE
When creating an association between assets, the created association is always between the parent and 0th in the tail list

### ISSUE THREAD

**Issue by fffe0d0a** [cairis-platform/cairis#569]
There seems to be an issue with the fix to issue #568 . Since the patch, while it is now possible to add an association located at the start of the tail list, it seems that this is now the only association is it possible to make.

In the provided model, an association between A and B is made correctly, but when an association between A and C is made, an association between A and B is made instead.

[cairis_zipped_for_github.zip](https://github.com/cairis-platform/cairis/files/5343158/cairis_zipped_for_github.zip)

**Comment by failys** [comment]
Opened and fixed cairis-platform/cairis-ui#76 . Can you please update CAIRIS and see if this problem still persists?

**Comment by fffe0d0a** [comment]
I can confirm that the issue is fixed. Many thanks.
