### ISSUE TITLE
500 Error with demo.cairis.org

### ISSUE THREAD

**Issue by baradhili** [cairis-platform/cairis#581]
### Expected behaviour
Demo works

### Actual behaviour
500 error when visiting site

### Steps to reproduce the behaviour
visit site

### Version of CAIRIS
current?

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Firefox current

**Comment by failys** [comment]
Thanks for flagging this.  There seemed to be issues with the mysql container during the nightly rebuilds. All should be good again now though.
