### ISSUE TITLE
500 Error with demo.cairis.org

### ISSUE THREAD

**Issue by bperment** [cairis-platform/cairis#586]
### Expected behaviour
Demo works

### Actual behaviour
500 error when visiting site

### Steps to reproduce the behaviour
visit demo.cairis.org

### Version of CAIRIS
current

### Details of browser or, if applicable, details of the OS used to host CAIRIS
FF current

**Comment by failys** [comment]
Thanks for spotting this.  The live demo should be online again now.  There seem to be some issues on AWS, so performance might be a bit spotty until I can get to the bottom of them.

**Comment by failys** [comment]
Closing for now as the site seems to be stable again.
