### ISSUE TITLE
Issue Navigating from One Page to Another

### ISSUE THREAD

**Issue by MRowland23** [cairis-platform/cairis#624]
### Expected behaviour
When on the 'Requirements > Goals' page, and navigate to the 'Risk > Countermeasures' page I should be taken to the countermeasures page, where I can view the countermeasures I have already created.

### Actual behaviour
When on the 'Requirements > Goals' page, then try navigate to 'Risk > Countermeasures', the url changes, yet the page remains on the Goals page, despite the URL changing to state that I am on the Countermeasures page.

### Steps to reproduce the behaviour
1. Go to 'Requirements > Goals'.
2. Try navigate to 'Risk > Countermeasures'

### Version of CAIRIS
CAIRIS v2.3.8

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Google Chrome - Version 90.0.4430.85 (Official Build) (x86_64)

**Comment by failys** [comment]
I see the problem, which occurs when you shouldn't be able to reach this page (because you don't have any valid risk responses).  I'lll take a look...

**Comment by failys** [comment]
Fixed by cairis-platform/cairis-ui#97
