### ISSUE TITLE
Connecting Cairis persona helper extension 

### ISSUE THREAD

**Issue by cryle2323** [cairis-platform/cairis#628]
Is the way to connect the extension to Cairis still the same as the short video on Brightspace... as this does not work for me.

**Comment by failys** [comment]
Can you please provide precise details of what you are doing in each step, what the results of each step are, and what you are expecting.  That video is only accessible to those with access to Brightspace @ BU.

**Comment by cryle2323** [comment]
Right click persona helper chrome extention - Connect to Cairis 

Set url as - http://localhost:7071

Enter username and password test combo then press login.

Login button is unresponsive with nothing happening.

**Comment by anonsecpreuser** [comment]
Did you start the UI up in development mode, ie cloning the cairis-ui repository and running ‘yarn run serve’.  You should check out the README in that repo for more info. Failing that, have you tried connecting the persons helper to the BU CAIRIS server?

**Comment by anonsecpreuser** [comment]
Also, you should check out the note here: https://cairis.readthedocs.io/en/latest/personas.html#online-affinity-diagramming-with-trello  .

**Comment by failys** [comment]
Closing as this doesn't seem to be a core CAIRIS.  Do re-open if you can provide instructions for reproducing the problem.
