### ISSUE TITLE
CAIRIS  Log In Page Unresponsive

### ISSUE THREAD

**Issue by josh74uk** [cairis-platform/cairis#629]

**Comment by failys** [comment]
Login via the Iive demo seems fine.  Can you describe how I might reproduce this problem?

**Comment by josh74uk** [comment]
when I press live demo and then log in with my credentials it  doesn't log  me in, but test account works

**Comment by josh74uk** [comment]
when I go to reset my password it says that my email address doesn't exist

**Comment by josh74uk** [comment]
even though I've created an account and done hours of work on it

**Comment by failys** [comment]
Live demo accounts are dropped every weekend.  When did you create the account?

**Comment by josh74uk** [comment]
i created it last week  in order to do my assignment. I was unaware of the account dropping as it didn't do that before with my previous account

**Comment by josh74uk** [comment]
is there  any way you  can recover  the account so I can export the work i have completed?

**Comment by failys** [comment]
I'm afraid not.  The live demo accounts are backed up during the week they are live (in case something happens when rebuilding the CAIRIS containers), but the backups are dropped along with the accounts at the end of the week.
