### ISSUE TITLE
Cairis not loading login page

### ISSUE THREAD

**Issue by cryle2323** [cairis-platform/cairis#630]
### Expected behaviour

When I press the live demo button I do not get sent to a login page.

### Actual behaviour

I press live demo button and nothing happens. 

### Steps to reproduce the behaviour

.... Press live demo button

I wanted to let you know ASAP that this is an issue, if possible could this please be looked at ASAP as work is due in less than a handful and weeks and this is putting it on a complete halt.

**Comment by failys** [comment]
Should be back online now
