### ISSUE TITLE
Package not importing 

### ISSUE THREAD

**Issue by cryle2323** [cairis-platform/cairis#631]
### Expected behaviour

I exported my work as a .cairis file yesterday. I am now trying to import it into cairis but when I press the import button I get a red X at the bottom of the page.

### Actual behaviour

Red X at the bottom of the page when importing cairis work

### Steps to reproduce the behaviour

Import a cairis package.

**Comment by cryle2323** [comment]
What do I do to successfully import my Cairis work?

**Comment by failys** [comment]
Have you followed the instructions here: https://cairis.readthedocs.io/en/latest/io.html#importing-models

**Comment by failys** [comment]
if it doesn't work then let me know.

**Comment by cryle2323** [comment]
Yes I have followed this to the exact step. 

I saved my work as a .cairis and am attempting to import the model using the .cairis model.

**Comment by failys** [comment]
Please email the model to shamal.faily@gmail.com, so I can take a look.

**Comment by failys** [comment]
Closing as this seems to be something that can't be reproduced.
