### ISSUE TITLE
Importing failure

### ISSUE THREAD

**Issue by cryle2323** [cairis-platform/cairis#632]
### Expected behaviour

cairis / xml model imports 

### Actual behaviour

![image](https://user-images.githubusercontent.com/65679672/128369073-2b57a455-bd8c-4bef-8cd4-6f3148729059.png)

### Steps to reproduce the behaviour

I have emailed both files of my cairis model for you to import.

**Comment by failys** [comment]
As a workaround, remove the & in line 154 / col 22 of your [XML] model file.
