### ISSUE TITLE
Journalctl reporting errors on Ubuntu 20.04

### ISSUE THREAD

**Issue by s1nglethr3ad** [cairis-platform/cairis#635]
### Expected behaviour
Followed, Installation and configuration via GitHub (automated) on a fresh Ubuntu 20.04 vm.

Run journalctl with no errors.

### Actual behaviour
Followed Installation and configuration via GitHub (automated) on a fresh Ubuntu 20.04 vm.

journalctl reports:
Dec 07 06:20:37 ubuntu cairisd.py[1329]:   File "/usr/local/lib/python3.8/dist-packages/flask_script/__init__.py", line 15, in <module>
Dec 07 06:20:37 ubuntu cairisd.py[1329]:     from flask._compat import text_type
Dec 07 06:20:37 ubuntu cairisd.py[1329]: ModuleNotFoundError: No module named 'flask._compat'
Dec 07 06:20:37 ubuntu systemd[1]: cairis.service: Main process exited, code=exited, status=1/FAILURE
Dec 07 06:20:37 ubuntu systemd[1]: cairis.service: Failed with result 'exit-code'.
Dec 07 06:20:37 ubuntu systemd[1]: cairis.service: Scheduled restart job, restart counter is at 5.
Dec 07 06:20:37 ubuntu systemd[1]: Stopped cairisd.
Dec 07 06:20:37 ubuntu systemd[1]: cairis.service: Start request repeated too quickly.
Dec 07 06:20:37 ubuntu systemd[1]: cairis.service: Failed with result 'exit-code'.
Dec 07 06:20:37 ubuntu systemd[1]: Failed to start cairisd.

### Steps to reproduce the behaviour
Install new Ubuntu 20.04 vm in VMWare fusion on Macbook.
Follow "Installation and configuration via GitHub (automated)"
run "journalctl -u cairis.service -f"

### Version of CAIRIS
Latest

### Details of browser or, if applicable, details of the OS used to host CAIRIS
user@ubuntu:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by failys** [comment]
@s1nglethr3ad  : this should be fixed now.  When I run "sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt install curl -y && sudo apt install net-tools -y && curl -s https://cairis.org/quickInstall.sh | bash -s my-secret-pw" , everything looks ok in the logs, and all appears to be good when I login to CAIRIS using Chromium on the VM.  

If you get any problems, please let me know and I'll re-open this issue.

**Comment by s1nglethr3ad** [comment]
> @s1nglethr3ad : this should be fixed now. When I run "sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt install curl -y && sudo apt install net-tools -y && curl -s https://cairis.org/quickInstall.sh | bash -s my-secret-pw" , everything looks ok in the logs, and all appears to be good when I login to CAIRIS using Chromium on the VM.
> 
> If you get any problems, please let me know and I'll re-open this issue.

Thank for looking into this.  I will test out today.

**Comment by s1nglethr3ad** [comment]
@failys, Works!  Thank you :)
