### ISSUE TITLE
Cannot log in to https://demo.cairis.org/

### ISSUE THREAD

**Issue by RodneyRichardson** [cairis-platform/cairis#638]
### Expected behaviour
* Open https://demo.cairis.org/
* Enter username/password of test/test (as mentioned here: https://cairis.org/cairis/cloud/), and click Login
* A model is shown (or something!)

### Actual behaviour
* Entering the username and password just returns to the login page. No error is displayed. 
* I also tried "cairis_test" as the username and password, with the same results.

### Version of CAIRIS
* Live demo

### Details of browser or, if applicable, details of the OS used to host CAIRIS
* Latest Chrome on Window 10.

**Comment by failys** [comment]
Thanks for the heads up.  The live demo is fine, but the login instructions on https://cairis.org/cairis/cloud/ are out of date.  The login should be 'test@test.com' not 'test'.

**Comment by RodneyRichardson** [comment]
Brilliant. Thanks for fixing.
