### ISSUE TITLE
[Feature request] multiple projects management

### ISSUE THREAD

**Issue by yuuyins** [cairis-platform/cairis#642]
### Expected behaviour
Feature for creating and managing multiple projects.

### Actual behaviour
Only able to create/manage one project per CAIRIS installation.

### Steps to reproduce the behaviour
go to `/properties`.

### Version of CAIRIS
I'm using latest image from dockerhub.

### Details of browser or, if applicable, details of the OS used to host CAIRIS
docker

**Comment by failys** [comment]
You can create more than one project / database at a time: https://cairis.readthedocs.io/en/latest/databases.html#cairis-databases
However, you can only have one open at a time if you are using the UI.  There are more options available if you're using the API though.

**Comment by yuuyins** [comment]
@failys oh i see. that suffices my needs, thank you very much! maybe just the terminology could be changed to make it more transparent (e.g. instead of "databases", call it "projects").

**Comment by failys** [comment]
You're right.  This could be better explained.  I'll open up a new issue for this.
