### ISSUE TITLE
VM/Vagrant not working. (After destroying and installing again)

### ISSUE THREAD

**Issue by mehrdadasadiut** [cairis-platform/cairis#646]
### Windows 10 , google chrome

![vagrant up1](https://user-images.githubusercontent.com/111504275/185574329-1e3eac91-b509-42b4-8599-aaca483e5656.PNG)
![vagrantup2](https://user-images.githubusercontent.com/111504275/185574471-4f0b3787-86ea-4761-b69b-0053050bbcc9.PNG)

**Comment by failys** [comment]
Can you please try deleting the VM and the cairis directory you cloned from GitHub and start the process from scratch.  There might be metadata hanging about that might be causing problems.

**Comment by mehrdadasadiut** [comment]
Yeah still having the same problem.
issue with the VM is fixed however.
![still error](https://user-images.githubusercontent.com/111504275/185595882-9cc9c41a-cc92-40f1-ad8c-d2d718a74759.PNG)

Please help

**Comment by failys** [comment]
If you're using Vagrant, you need to connect to http://localhost:7071

**Comment by mehrdadasadiut** [comment]
Yeah I know, I tried to both but didn't screenshoted this. Still no connection.

**Comment by mehrdadasadiut** [comment]
As you can see, I tried to ping the host:port but there is no connection.

**Comment by mehrdadasadiut** [comment]
Here also error when I try to use vagran't terminal for connecting to the port.
![terminal vagrant](https://user-images.githubusercontent.com/111504275/185597104-b54dcb45-4424-4cc8-9f6e-4dc9368d92e3.PNG)

**Comment by mehrdadasadiut** [comment]
Here is also the connection showed in netstat , you can see the details of the port
![tempsnip](https://user-images.githubusercontent.com/111504275/185602212-6a0aaa1f-af1f-414a-9171-ee4e237a7543.png)

**Comment by failys** [comment]
Strange - the output of your curl command should look like this (from something I've just provisioned by following the same instructions
<img width="1092" alt="Screenshot 2022-08-19 at 3 06 47 PM" src="https://user-images.githubusercontent.com/1562162/185636808-fe0d81e9-2655-40e1-8c3e-f6f2c284a0b1.png">
)

**Comment by failys** [comment]
Can you please try opening your browser to http://localhost:7071, and then, in the VM, running `journalctl -u cairis | tail` ?
You should get something like the below
<img width="1092" alt="Screenshot 2022-08-19 at 3 09 25 PM" src="https://user-images.githubusercontent.com/1562162/185637350-63c9e61e-ab84-4555-a547-636e64127b09.png">
:

**Comment by mehrdadasadiut** [comment]
I am starting the CAIRIS using the Docker guidelines now. 
Due to this, the VM is not going to work anymore and I do need to change some settings such as Hyper V.

**Comment by failys** [comment]
Changes made to the quickInstall.sh script should have fixed this, so I'm closing for now.  Let me know if this needs to be re-opened though.
