### ISSUE TITLE
Data insertion error (for example requirement)

### ISSUE THREAD

**Issue by mehrdadasadiut** [cairis-platform/cairis#648]
### Expected behaviour
Add requirement

### Actual behaviour
Error when I enter requirement

### Steps to reproduce the behaviour
Enter Requirement field and write the details

### Version of CAIRIS

latest
### Details of browser or, if applicable, details of the OS used to host CAIRIS

firefox , windows 10

![requiremt insertation error](https://user-images.githubusercontent.com/111504275/185609357-4f66cc10-9be2-49a7-aa3a-0e4c55f80137.PNG)

**Comment by failys** [comment]
Thanks for flagging this.  You shouldn't be allowed to create a requirement without indicating the asset associated with it, so something has gone wrong somewhere.  I'll take a look.

**Comment by failys** [comment]
I've just pushed a fix to the cairis-ui repository which should fix this.
