### ISSUE TITLE
If Processes in a DFD are Use Cases in CAIRIS, how do we add threats for a process such as web server?

### ISSUE THREAD

**Issue by gmaran23** [cairis-platform/cairis#651]
### Expected behaviour
None

### Actual behaviour
None

### Steps to reproduce the behaviour
None

### Version of CAIRIS
Pulling the latest docker images

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Ubuntu

### Question
If Processes in a Data Flow Diagram are created as "Use Cases" in CAIRIS according to the documentation here - https://cairis.readthedocs.io/en/latest/threats_tm.html#adding-updating-and-deleting-entities-processes-and-data-stores
are there any ways to represent threats that are specific to a Process in a Data Flor Diagram?

__Example:__
Usually things like API Gateway, or Web Servers are listed as Processes in a Data Flow Diagram. These processes are then considered as technical assets. These Processes might have vulnerabilities and threats of their own. 

How can we tag a vulnerability to a Processes (that is a use case) in CAIRIS? What are some ideas?
Also the Models -> Assets would not show Processes in a Data Flow Diagram, because they are Use Cases in CAIRIS?

I have used diagrams.net with CAIRIS shapes to import threat model.

Based on my current usage of CAIRIS, I can say that what I am asking for is currently not possible, but I might have missed something by oversight. Your response is appreciated.

**Comment by failys** [comment]
tldr; - Yes and threats to the process show up the threat model tab on home page.  However, you need to think beyond just the DFD.

* Longer explanation

In CAIRIS (and general data flowing money), a 'process' isn't some really a piece of software or hardware, but some activity that does something.  So, if we're threat modelling a web-based payroll system, the process will be something like 'Handle Payroll request'  .  For CAIRIS to acknowledge threats to this process, you also need to (i) stipulate goals that the use case puts in context (e.g. payroll requests shall be received from a trusted source), (ii) 'obstruct' the goal with an obstacle - the basis of your threat (e.g. payroll request changed), (iii) create a threat (e.g. POST request tampering) linked to your obstacle.  

The attached model should illustrate what I mean. [change_prefix_to_xml.txt](https://github.com/cairis-platform/cairis/files/9467967/change_prefix_to_xml.txt)

This might all sound a bit involved, but there are all sorts of advantages to this approach.
1.  CAIRIS is methodology agnostic, so you could use whatever method you want to find your threats, e.g. STRIDE, LINDDUN if you're capturing privacy data, STPA for things safety related, etc.2. 
2.  CAIRIS assumes that you're not threat modelling on your own, and others will want to walk over what you've been doing, and challenge the basis of why things in the model are the way they are.  By making you state your assumptions about the assets you want to protect, requirements that give rise to processes, and the reasoning behind your threats, your threat models will not only stand up to scrutiny, you'll also get ideas about other threats, vulnerabilities and risks.3. 
3.  The more data you add, the more you can reason about the model as it evolves.  For example, if you validate this model then you'll see CAIRIS has already flagged a few security and privacy problems that probably didn't think about just looking at the DFD.  For more info about what we mean by 'post-process taint', you might be interest in [this](https://arxiv.org/abs/2006.04098).

Hope this makes sense.

**Comment by gmaran23** [comment]
Thank you very much for the clarification. I also stumbled upon the documentation that exactly states what you have described.

[How Obstacles relate to undesired behavior, and how undesired behavior can lead to vulnerabilities](https://cairis.readthedocs.io/en/latest/gro.html#goals-requirements-and-obstacles)

Your explanation ties the pieces of Use Cases (Process in a DFD), Goals, Obstacles, and Threats.

Well done Sir. Thank you.
