### ISSUE TITLE
400 errors throughout demo

### ISSUE THREAD

**Issue by lucasgonze** [cairis-platform/cairis#653]
demo.cairis.org is showing errors thrown in a wide variety of contexts. Most pages I have tried have be non-functional. Error messages have the common theme of MySQL problems. 

Screen shot:
<img width="723" alt="image" src="https://user-images.githubusercontent.com/111581/190293471-20aedb63-86d9-4bb0-8874-08169ceba1f6.png">

### Steps to reproduce the behaviour

For example:
1. UX menu > Environments
2. + button 
3. enter values in each form field
4. Submit form with "Create" button
5. Get Mysql error "Unknown database"

### Details of browser or, if applicable, details of the OS used to host CAIRIS

Firefox on OS X

**Comment by failys** [comment]
I've just logged into the live demo and everything looks fine.   This is the sort of error you get when you either (i) try logging in during the nightly rebuild, or (ii) login before the nightly rebuild and try interacting with the demo either afterwards, i.e. when your browser session corresponds with a database connection that is no longer around.  In any event, try closing the browser/browser tab, clearing your cache and logging back in.

**Comment by failys** [comment]
Is this still an issue?  I'll close this down if not.

**Comment by lucasgonze** [comment]
The demo is now working.
