### ISSUE TITLE
Errors with Demo

### ISSUE THREAD

**Issue by parakats** [cairis-platform/cairis#655]
### Expected behaviour
Import XMLs/Cairis models

### Actual behaviour
Red X appears at bottom of screen with no error message and no import occurs

### Steps to reproduce the behaviour
Try import an XML or Cairis package

### Version of CAIRIS
Demo version

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Chrome Browser

There is also no link to the Ubuntu VM box it takes you to a google drive that is 404ed and so using the Demo is my only option as vagrant is constantly failing to build correctly and docker also having issues

**Comment by parakats** [comment]
Also fails to import on Microsoft Edge

**Comment by failys** [comment]
Can you please upload the model you're trying to import, so I can take a look?

**Comment by parakats** [comment]
It's any model I've created all models both CAIRIS models and XML fail to import, not wanting to post the model here due to it being uni work

**Comment by failys** [comment]
It must be something specific about whatever it is you're creating.  I've tried importing an arbitrary model, and I don't see any problems.  Did you check your model for reserved characters: https://cairis.readthedocs.io/en/latest/reserved.html ?  This is a fairly common source of import problems.  Failing that, try creating a minimal model that doesn't import and I can take a look.

**Comment by parakats** [comment]
Found the issue, where I had copy and pasted my exerts some had unusual characters in them from the website formatting. Went through the XML and all fixed thank you
