### ISSUE TITLE
server dies while installation.

### ISSUE THREAD

**Issue by mehrdadasadiut** [cairis-platform/cairis#657]
### Expected behaviour
CAIRIS install successfully

### Actual behaviour
server dies before installation (see picture)

### Steps to reproduce the behaviour
install cairis using "Installation and configuration of server with account registration via GitHub (automated)"

### Version of CAIRIS
latest

### Details of browser or, if applicable, details of the OS used to host CAIRIS
LINUX ubuntu 20  , 16 gb ram 16 vCore 10 gb storage

<img width="901" alt="serverdies" src="https://user-images.githubusercontent.com/111504275/215275890-2710b60f-fafa-44e6-9d07-7d883d706760.PNG">

**Comment by mehrdadasadiut** [comment]
I get the same error when followed the path of "install from github manually).
One I finish the quickstart.py part and make the configurations, the error : 
[AttributeError: module 'sqlalchemy.orm' has no attribute 'DeclarativeMeta']
appears and no go further.

**Comment by mehrdadasadiut** [comment]
<img width="954" alt="Capture222" src="https://user-images.githubusercontent.com/111504275/215316877-c13d255c-3142-4e3d-a23a-8cac80cc8670.PNG">

**Comment by failys** [comment]
It sounds like a problem relating to the recent SQL Alchemy update that is breaking Flask Security, but I'll take a look.

**Comment by mehrdadasadiut** [comment]
Do you think that you can help me fix it soon? We need to deploy CAIRIS for our project on a linux ubuntu server.
Or is there any other version of SLQ Alchemy that fix the issue meanwhile?
Actually I followed all installation guidelines (different onces) and none of them resulted successfully..

**Comment by failys** [comment]
If you need something now then have you tried using the CAIRIS docker container?  The live demo seems ok, so this should be ok for you too.  I'm looking at this now though.

**Comment by mehrdadasadiut** [comment]
Yes already tried the container also. Please look at the other issue I made. The server gives an internal error on localhost:80 and not responding. Although as you can see the containers were running (docker ps)

**Comment by mehrdadasadiut** [comment]
Thanks for helping out.

**Comment by failys** [comment]
I've pushed an update that should fix this problem.  Can you please try doing a clean automated install again?

**Comment by mehrdadasadiut** [comment]
ok I go for it right now.

**Comment by mehrdadasadiut** [comment]
The error did not appear anymore.
So that means localhost:8000 should provide the CAIRIS, right? The server is still inaccible using HTTP://localhost:8000 and its really strange.

**Comment by failys** [comment]
Depends on how you install it.  From Vagrant, it's accessible from http://localhost:7071

**Comment by failys** [comment]
I've done a clean install via Vagrant and everything seems good now.

**Comment by mehrdadasadiut** [comment]
I did not get any error this time. Meaning that the SQL Alchemy conflict is resolved by the recent push you have done.
