### ISSUE TITLE
Cannot run cairis using docker/ubuntu

### ISSUE THREAD

**Issue by mehrdadasadiut** [cairis-platform/cairis#658]
### Expected behaviour
CAIRIS run on localhost:80

### Actual behaviour
Server error and not showing.

### Steps to reproduce the behaviour
Install using Docker.

### Version of CAIRIS
latest

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Firefox, UBUNTU 20

Error accessing the service 
<img width="948" alt="error1" src="https://user-images.githubusercontent.com/111504275/215287929-eca08a7e-c629-417a-8a52-fb9067646855.PNG">

Containers are running.
<img width="946" alt="dockercontainer" src="https://user-images.githubusercontent.com/111504275/215287934-be3e5f7c-e65b-43e3-a9a8-d49590e27551.PNG">

**Comment by failys** [comment]
Did you try creating / starting the containers using:

`NET=cairisnet
docker network create -d bridge $NET
docker run --name cairis-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:latest --thread_stack=256K --max_sp_recursion_depth=255 --log_bin_trust_function_creators=1
docker network connect $NET cairis-mysql
docker run --name CAIRIS -d -P -p 80:8000 --net=$NET shamalfaily/cairis`

**Comment by failys** [comment]
Also, what happens if you try to access the URL via the shell, e.g. `curl http://localhost`

**Comment by mehrdadasadiut** [comment]
I am now trying to make another clean VM to go for another Docker installation.
I think this command does not include PDF (full exportability) right? 
Since there is no doc-container in this command.
The other command (sudo docker run --name cairis-docs -d -v cairisDocumentation:/tmpDocker -v cairisImage:/images -t shamalfaily/cairis-docs)    is not included.

**Comment by mehrdadasadiut** [comment]
<img width="667" alt="curlError" src="https://user-images.githubusercontent.com/111504275/215323604-86955d8b-5fe4-4b5c-9cfd-0779542a64f9.PNG">

Installed again and followed the procedure of Docker and still not working.
The image is from curl command.

**Comment by failys** [comment]
The docker images are being rebuilt for the latest update, so best to give this an hour or two before trying again.
