### ISSUE TITLE
Question: is it possible to change the type of Requirements?

### ISSUE THREAD

**Issue by mehrdadasadiut** [cairis-platform/cairis#664]
### Expected behaviour
Changing the name of Requirements. We have some types of Requirements that are not listed in the current requirement types of CAIRIS.
Which tables are needed to be modified and if it affect a running CAIRIS or not?

### Version of CAIRIS
latest

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Firefox/Chrome  - UBUNTU20.4

**Comment by failys** [comment]
If you _really_ want to do this then there is a requirement_type table.  The current types are inserted into the table in init.sql - just add rows for whatever types you want to support.  However, the requirement types are also stipulated in the XML DTDs, e.g. cairis_model.dtd and goals.dtd, so you'll need to modify that too.  You can't do this on a running server, so you'll want to export whatever you're working on, making the change, and restart the server and create a new database (i.e. to ensure init.sql runs)

**Comment by failys** [comment]
Come to think of it, you'll need to make a change to cairis-ui too, specifically Requirement.vue as the requirement types are coded locally there.

**Comment by mehrdadasadiut** [comment]
Sorry just to clarify, do I need to reinstall the CAIRIS from scratch? just stopping cairis and doing these changes will keep my current data or will it conflict and require reinstallation?

**Comment by failys** [comment]
You shouldn't re-install from scratch.  If you do, you will overwrite any changes you make.   Stopping CAIRIS, making the changes, and re-starting again should be sufficient.  You will, however, want to export models you currently have running, so you don't lose anything when init.sql is re-run (which will drop and re-create all the tables).
