### ISSUE TITLE
Diagrams.net DFD import issue 

### ISSUE THREAD

**Issue by atchaturvedi** [cairis-platform/cairis#669]
### Expected behaviour
Successful import of DFD created in Diagrams.net

### Actual behaviour
Throwing error "[Thu Sep 28 11:50:17.428916 2023] [wsgi:error] [pid 16:tid 140149428041280] [remote 172.17.0.1:44484] ERROR:cairisd:[400] Invalid XML input: The provided file is not a valid XML file"

### Steps to reproduce the behaviour
Got to System > Import Model, Select Model type to diagrams.net, browse and upload a sample draw.io diagram
An error message will appear as soon as we hit import button

### Version of CAIRIS
2.3.8

### Details of browser or, if applicable, details of the OS used to host CAIRIS
Firefox 115.3.0esr (64-bit), OS is windows, running Cairis on a docker container

**Comment by failys** [comment]
Did you follow the instructions at https://cairis.readthedocs.io/en/latest/threats_tm.html#modelling-dfds-with-diagrams-net?  If so, did you check whether any of the names given for DFD elements might be invalid XML characters, e.g. anything with an ampersand.  There are online XML linters like https://xmllint.com, which can help with the latter.

**Comment by failys** [comment]
No response.  Assuming query has been resolved.
