### ISSUE TITLE
Missing explanations

### ISSUE THREAD

**Issue by Otyg** [cairis-platform/cairis#673]
Hi,

I've been using CAIRIS for a while and I like it a lot. However I miss some explanations, or documentation, regarding som of the entries in the options-dropdown. 

More concrete I wonder how surface type, Protocols, Privileges and Access Rights is supposed to be used and what the score-field represents. For instance; is a surface type with a score of 0 more or less "dangerous" than a surface type with a score of let say 10?

Best regards!

**Comment by failys** [comment]
Hi Martin,

I'm glad to hear you find CAIRIS useful.

Have you looked at https://www.youtube.com/watch?v=k2XRVUJ44lM ?  This
summarises how to do architectural risk analysis in CAIRIS, and what is
meant by things like surface types, protocols, etc.  There is also this
paper which explains the theory behind those concepts:
https://www.researchgate.net/publication/262329588_Model-driven_architectural_risk_analysis_using_architectural_and_contextualised_attack_patterns

The documentation in CAIRIS should help explain this but, if it doesn't,
please feel free to raise an issue in CAIRIS for the specific area of
documentation you think needs elaboration.  I can take a look and add
whatever might be missing/needs better explaining.

Best Regards,

Shamal

**Comment by Otyg** [comment]
Hi Shamal,

Thank you for the links, I will check them out and I'll might come back with either an issue regarding specific areas of the documentation or a PR.

Best Regards,

Martin
